### PR TITLE
Structuring the Different Files in Different Folder

### LINKED ISSUE #7: Better Structure
Hey there! So this is very simple! I want to move the CSS to /css/ and also the javascript, images and all that in this project, dont forget to redirect all files. Example: If in the HTML I use a image and is "image.png" and you move it to "/img/image-1.png" dont forget to change it also in the HTML.

**Thanks**.

### PR DESCRIPTION
**Pull request by SahilShaw2004**
With their desired paths and also fixing a CSS for width 480px

### CODE REVIEW

**Comment by JollyJolli** [comment]
Hey, thanks for collaborating! This is something I wanted to do a few months ago, but I procrastinated. I really appreciate your help in getting it done. Before we merge it, could you please check if it appears on your Hacktoberfest website? I want to ensure everything is in order and avoid any issues!

**Comment by SahilShaw2004** [comment]
it is appearing in Hacktober fest website .
Thank You

**Comment by JollyJolli** [comment]
Noooo

**Comment by JollyJolli** [comment]
I was just finishing the review to merge

**Comment by JollyJolli** [comment]
Because of the problem to merge

**Comment by SahilShaw2004** [comment]
So do you merge or not ,i guess you closed why?

**Comment by JollyJolli** [comment]
No, I has merged other user of other thing and it afectes this one, so I was changing Somethings so it was able to merge, but you delete d your repository and it closed automatic 😭

**Comment by SahilShaw2004** [comment]
Don't know which one i deleted .Is that the forked one ?

**Comment by JollyJolli** [comment]
Yes

**Comment by SahilShaw2004** [comment]
So i didnt get the one merge ?😭

**Comment by JollyJolli** [comment]
I want to merge your edits ‼️‼️😭 but with your repository deleted is imposible 😫😫😫

**Comment by SahilShaw2004** [comment]
Ok no problem

**Comment by SahilShaw2004** [comment]
can you revert the changes such that i can again do that

**Comment by JollyJolli** [comment]
Cant you implement the new changes? or you want me to revert them?

**Comment by SahilShaw2004** [comment]
No revert the changes which i did i will again do that .then I got the merge hopefully.Is this possible?

**Comment by JollyJolli** [comment]
I didn't merge your changes yet, so you can start from 0, or i dont get it

**Comment by JollyJolli** [comment]
I have never merged your changes but i want to

**Comment by SahilShaw2004** [comment]
OK i forked again and this time i m not going to delete it 😅.Making a pr in few minutes

**Comment by JollyJolli** [comment]
Perfect! Now i will merge your PR just as you publish it!

**Pull request closed without merging**
