### PR TITLE
Restructuring of Files into respective Folders

### PR DESCRIPTION
**Pull request by SahilShaw2004**
For the second time the changes which i did earlier

### CODE REVIEW

**Comment by JollyJolli** [comment]
I LOVE YOU

**Comment by JollyJolli** [comment]
READY!!!!!

**Comment by SahilShaw2004** [comment]
Love You Bro.Thanks

**Comment by JollyJolli** [comment]
Now you can delete your repo! And confirm to me that this apper on your hacktoberfest website

**Comment by SahilShaw2004** [comment]
Until now it is not showing it showing that of the prev one .but for the one i did recently it is not

**Comment by JollyJolli** [comment]
It can take up to 6 hours :(

**Comment by SahilShaw2004** [comment]
It is showing now😍

**Comment by JollyJolli** [comment]
Perfect! Im happy it had work! If you want other easy issue, or other easy PR for hacktober check my other repo (specificly for hacktoberfest) [here is my other repo](https://github.com/JollyJolli/HacktoberWall/)

**Comment by SahilShaw2004** [comment]
OK Thanks i will surely visit in few days .

**Comment by JollyJolli** [comment]
Perfect! Have a nice day

**Pull request merged**
