### PR TITLE
feat: Added the English language

### LINKED ISSUE #9: Make the web multi-language
So the web is in spanish and i want the page to be in English and Spanish. You can do it how ever you want to.

### PR DESCRIPTION
**Pull request by NamanSriva**
feature: This PR added the functionality to change the language between spanish and english. I used JavaScript logic to switch between languages. I also made the page to fetch projects from a static file. I converted your online json file to create an array and fetched project details from there and also it's easy to switch between languages fro project title and description. In case if online URL doesn't work or crashes then your offline json file will be used to fetch the data.

Screenshots --
Screenshot (96)
Screenshot (97)

Issues-

Feat #9

### CODE REVIEW

**Comment by JollyJolli** [comment]
Hey there! Thanks for countributing! But there is a small problem! Can you add back the publicity? After that i will be very happy to merge this PR, thanks 🫶🏻
Screenshot:
image

**Comment by NamanSriva** [comment]
Yep Sure I'll do that ASAP

**Comment by JollyJolli** [comment]
Thanks

**Comment by NamanSriva** [comment]
I added those sections and committed the changes. Hope the changes are visible now.
Screenshot (99)
Screenshot (98)

**Comment by JollyJolli** [comment]
Thanks!

**Pull request merged**
