### PR TITLE
fix: format clickable toc; add LICENSE backlink

### PR DESCRIPTION
**Pull request by pizofreude**
I fix the format for clickable TOC with emojis and added proper backlink for LICENSE file in the README.

### CODE REVIEW

**Comment by JollyJolli** [comment]
Thanks For doing this! ‼️🫶🏻

**Comment by JollyJolli** [comment]
If you want to help with other hacktober-fest project i have one called "HacktoberWall" and is very easy to contribute

**Comment by pizofreude** [comment]
Sure thing, I'll have a look later 🥇

**Comment by JollyJolli** [comment]
Perfect! Have a nice day

**Pull request merged**
